### ISSUE TITLE
HopVertical command not work

### ISSUE THREAD

**Issue by boomker** [smoka7/hop.nvim#19]
**Describe the bug**
`HopVertical` command not work

**To Reproduce**
In nvim  Command mode exec `HopVertical`

```
-- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
        end
        vim.opt.runtimepath:prepend(lazypath)

-- install hop.nvim:
editor["smoka7/hop.nvim"] = {
	lazy = true,
	event = "VeryLazy",
	config = require("editor.hop"),
}
--- How You use hop...

```
**Expected behavior**
In nvim command mode exec `HopVertical`, it work

**Screenshots**
<img width="1440" alt="image" src="https://github.com/smoka7/hop.nvim/assets/19751472/ddb46a12-2a72-42d3-9efc-341a75a98d77">

**version (please complete the following information):**
 - Nvim version: 0.9.1
 - hop.nvim version: latest, commit: 31e0e42

**Additional context**

**Comment by smoka7** [comment]
can't reproduce this either.  `table.unpack` is a lua library function.I think source of your problems are somewhere else.

**Comment by davideliseo** [comment]
Having the same issue on a clean install, with the same error messages as OP. Let me know if there's anything we can do to help you debug this.

**Comment by smoka7** [comment]
what's your nvim version?

**Comment by boomker** [comment]
> Having the same issue on a clean install, with the same error messages as OP. Let me know if there's anything we can do to help you debug this.

---
<img width="841" alt="image" src="https://github.com/smoka7/hop.nvim/assets/19751472/9997044f-e1bf-4876-a690-093848dbe243">
I made a small change to the source code, and it works
