### ISSUE TITLE
Not possible to set custom highlight colors

### ISSUE THREAD

**Issue by RayJameson** [smoka7/hop.nvim#20]
Colors are overwritten by the plugin no matter what way I try to change them. I believe it's because of commit 90e078a
It is possible when using origin version of the plugin

**Comment by smoka7** [comment]
you could overwrite it like this
```lua
vim.api.nvim_create_autocmd('ColorScheme', {
    callback = function()
    vim.api.nvim_set_hl(0, 'HopNextKey', { fg = '#00dfff', bold = true, ctermfg = 198, cterm = { bold = true } })
    end,
})
```
