### ISSUE TITLE
Incompatibility with nvim-treehopper

### ISSUE THREAD

**Issue by BrunoKrugel** [smoka7/hop.nvim#21]
[nvim-treehopper](https://github.com/mfussenegger/nvim-treehopper) works fine with original hop, but not with this fork.

```
E5108: Error executing lua: ...ugel/.local/share/nvim/lazy/nvim-treehopper/lua/tsht.lua:301: ...rugel/.local/share/nvim/lazy/hop.nvim/lua/hop/window.lua:74: attempt to index local 'opts' (a nil value)
stack traceback:
	[builtin#36]: at 0x01047bc61c
	...ugel/.local/share/nvim/lazy/nvim-treehopper/lua/tsht.lua:301: in function 'move'
	/Users/bruno.krugel/.config/nvim/lua/custom/mappings.lua:405: in function </Users/bruno.krugel/.config/nvim/lua/custom/mappings.lua:404>
```

**Comment by smoka7** [comment]
It looks like treehopper never passes any option to [hop](https://github.com/mfussenegger/nvim-treehopper/blob/5a28bff46c05d28bdb4bcaef67e046eb915a9390/lua/tsht.lua#L213) and hop ignored it before.
Some of fixes added here need the `opts` value to be set and working around it is not an option.

**Comment by smoka7** [comment]
The linked pr doesn't close this exactly but offers an alternative to treehopper.
