### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by FelipeLema** [smoka7/hop.nvim#22]
**Describe the bug**
The repo is missing tests. Why a repo is should have tests is a given

**To Reproduce**

**Expected behavior**

Have tests ran in pull requests

**Screenshots**

**version (please complete the following information):**

**Additional context**

See https://github.com/phaazon/hop.nvim/pull/271 for a first approach. Still dunno why was it closed.

**Comment by smoka7** [comment]
I'm favor of adding it.
could you open the pr here?
