### ISSUE TITLE
How to use with select/delete/change/yank etc

### ISSUE THREAD

**Issue by scrotty** [smoka7/hop.nvim#31]
I feel like a bit of an idiot. In the feature list I see that hop can be used "with commands like v, d, c, y to visually select/delete/change/yank up to your new cursor position." My assumption is that I could initiate, say, delete as usual by pressing the 'd' key. Then I'd be able to press a second key as part of the delete "chord" to invoke hop. Whatever hop matched would be deleted.

I put the following in my init.lua:
vim.api.nvim_set_keymap('n', 'dh', ':HopChar1\<CR>', { noremap = true, silent = true })

(Normally dh would delete left, but I wanted to invoke hop instead.)

What this actually seems to do is exit the delete and then do a standard hop.char1. That is, no deletion occurs.

I'm guessing I'm missing something very simple. Could you help me figure out how to properly integrate hop into select/delete/change/yank via key chords? TIA!

**Comment by smoka7** [comment]
I think there is no documentation on this.
You have to map hop in `operator-pending-mode` like this.
`vim.api.nvim_set_keymap({'n','o'}, 'dh', ':HopChar1<CR>', { noremap = true, silent = true })`

**Comment by scrotty** [comment]
Thank you, smoka7! I needed to modify a bit to work for my case, but your insight in `operator-pending-mode` was exactly what I needed.
`vim.keymap.set("o", "h", '<Cmd>HopChar1<CR>', { remap = true, silent = true })`

**Comment by scrotty** [comment]
For anyone who might read this in the future, I ultimately found this to be my best solution:
`vim.keymap.set("o", "h", ":lua require'hop'.hint_char1({hint_offset=-1})<cr>", { remap = true, silent = true })`

**Comment by toejough** [comment]
Just dropping in to echo that while the vim commands work fine for normal mode, to get them to work with visual mode I needed to use the API.

This worked fine in normal mode, but if I tried to add the "v" mode option I got an error ("no range allowed"):
```lua
local wk = require("which-key")
wk.register({ -- normal mode
	["m"] = {
		name = "+move",
		w = { ":HopWord<cr>", "words" },
		p = { ":HopPattern<cr>", "pattern" },
		v = { ":HopVertical<cr>", "vertical" },
		h = { ":HopWordCurrentLine<cr>", "horizontal" }
	}
})
```

Whereas this worked just fine:
```lua
local wk = require("which-key")
local hop = require("hop")
wk.register({ -- normal AND visual mode
	["m"] = {
		name = "+move",
		w = { hop.hint_words, "words" },
		p = { hop.hint_patterns, "pattern" },
		v = { hop.hint_vertical, "vertical" },
		h = { function() hop.hint_words({ current_line_only = true }) end, "horizontal" }
	},
}, {
	mode = { "n", "v" },
})

```
