### ISSUE TITLE
Better yank and paste

### ISSUE THREAD

**Issue by Weissle** [smoka7/hop.nvim#45]
Do you know this plugin? https://github.com/Weissle/easy-action.git 
If you think this plugin's design is good, I would like to let it integrate with hop.nvim.

**Comment by smoka7** [comment]
I haven't used it but the idea seems good at a first glance.
Is there any advantage for adding it into hop instead of creating it as a extension?

**Comment by Weissle** [comment]
Originally it was an extension. But I saw that the new commands `HopYankChar1` and `HopPaste`  have similar features with that plugin.

**Comment by smoka7** [comment]
For new features that could be written as an extension, I prefer it to be separate from the core so we can keep the code base small.
But if you think your extension could benefit from changes to the core feel free to contact, I help as best as I can.
Other than that I think having a list of compatible extensions in the Readme is good.

**Comment by Weissle** [comment]
sure.
