### ISSUE TITLE
Is there a method to solve this the use case? A same buffer in some split windows?

### ISSUE THREAD

**Issue by ysl2** [smoka7/hop.nvim#48]
For short, a buffer in some splits, when using hop.nvim, the prompts in these windows are same. But I want to navigate between these windows, so I need the different prompts for specific window.

You can refer this issue to more specific use case:

https://github.com/phaazon/hop.nvim/issues/244

**Comment by smoka7** [comment]
Hop shows hints with `nvim_buf_set_extmark()` that works with buffers so I don't think it's possible to create  different extmarks for each window. see https://github.com/neovim/neovim/issues/19654.
