### ISSUE TITLE
HopWordMW seems to not work cross-window from within terminal buffers (normal mode)

### ISSUE THREAD

**Issue by kekscode** [smoka7/hop.nvim#49]
**First things first**

First of all: Thank you so much for this great plugin, i love it a lot and appreciate the work!

**Describe the bug**

The `HopWordMW` user command does not allow me to hop to a window outside a terminal buffer (in normal mode).

**To Reproduce**

I have this configuration:

```
-- install and configure hop.nvim
  {
    'smoka7/hop.nvim', -- hopping arround
    version = "*",
    config = function()
      require('hop').setup {
        multi_windows = true,
      }
    end
  },

-- hop arround anywhere cross windows
vim.api.nvim_set_keymap("n", "f", "<cmd>HopWordMW<CR>",
  { noremap = true, silent = true, desc = "Hop anywhere cross windows" })
```

**Expected behavior**

Use the command mapping to hop from any visible split window to any other visible split window.

**Screenshots**

hop'ing from a normal text buffer (multi windows works)r:

<img width="961" alt="image" src="https://github.com/smoka7/hop.nvim/assets/803252/ea52d6e6-cad5-497f-b490-9767a34d3d9d">

hop'ing from a terminal buffer in normal mode (multi windows does not work on my machine):

<img width="961" alt="image" src="https://github.com/smoka7/hop.nvim/assets/803252/22597ff5-cd1b-4f68-9e33-35e8451a0b2e">

**version (please complete the following information):**

NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

with latest hop version:

```
version 2.3.1
tag     v2.3.1
branch  master
commit  f2508f4
```

**Comment by smoka7** [comment]
I can reproduce this but I could not find what's causing it.

**Comment by smoka7** [comment]
Never mind, found the culprit.
