### ISSUE TITLE
How to configure custom highlights without hop.nvim overriding

### ISSUE THREAD

**Issue by hellodhruvin** [smoka7/hop.nvim#50]
I need some guidance on configuring custom highlights in this plugin. Currently, I'm using a Lua file to set custom highlights like this:
```lua
local function set_hl(group, tbl)
  vim.api.nvim_set_hl(0, group, type(tbl) == 'table' and tbl or { fg = tbl })
end

set_hl('HopNextKey', { fg = '#ffffff', bg = '#ff007c', bold = true })
set_hl('HopNextKey1', { fg = '#ffffff', bg = '#00dfff', bold = true })
set_hl('HopNextKey2', { fg = '#ffffff', bg = '#2b8db3' })
set_hl('HopUnmatched', { fg = '#666666', sp = '#666666' })
```

While this works, I noticed that when I set custom highlights in my Lua file, they get overridden by hop.nvim, making me re-require the Lua file after hop setup.

Is there a more streamlined way to define custom highlights without this overriding issue in hop.nvim? Any guidance or suggestions would be greatly appreciated.
(I have already disabled the 'create_hl_autocmd' option if that's relevant)

https://github.com/smoka7/hop.nvim/blob/1cbaa79457e6b5e9b04e6d5d8d19bd6b65ffa2be/lua/hop/init.lua#L586

**Comment by smoka7** [comment]
Set `create_hl_autocmd = false` and change your highlights after `require('hop').setup()`.
