### ISSUE TITLE
hint_lines_skip_whitespace doesn't include folds

### ISSUE THREAD

**Issue by gerazov** [smoka7/hop.nvim#62]
If there are folds in the buffer they are ignored when using `hint_lines_skip_whitespace`:

![Screenshot_20231230_200702](https://github.com/smoka7/hop.nvim/assets/15214418/fbb257d5-d398-44c7-ab03-60007c0b0d9b)

**Comment by smoka7** [comment]
It could be confusing to do this. Cause the text shown in the place of closed fold could differ from the actual text on that line And `vim.api.nvim_win_set_cursor()` sets the cursor position on the actual line not the shown text.

**Comment by gerazov** [comment]
It's a pity if it doesn't get implemented - it would be very useful for files where the majority of lines are folded. 
For example, I work with `org` files where all headlines are folded so the whole buffer is nothing but folded lines. Then when you run hop you get the following results:

![image](https://github.com/smoka7/hop.nvim/assets/15214418/23de3ac0-bb7f-4837-b346-78e83900ad95)
