### ISSUE TITLE
:HopPattern not working

### ISSUE THREAD

**Issue by AdamSundberg** [smoka7/hop.nvim#63]
**Describe the bug**
:HopPattern not working. Results in a `ipairs` error.

**To Reproduce**
```
-- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
        end
        vim.opt.runtimepath:prepend(lazypath)

-- install hop.nvim
        local plugins = {
          { "smoka7/hop.nvim", opts = {} },
        }
        require("lazy").setup(plugins,{})
--- How You use hop...
:HopPattern
<insert pattern> + Enter
```
**Expected behavior**
The pattern searched for gets highlighted.

**Screenshots**
<img width="1238" alt="image" src="https://github.com/smoka7/hop.nvim/assets/25883712/009560fb-b62b-43eb-83fe-061373578a68">

**version (please complete the following information):**
 - Nvim version: NVIM v0.9.2
 - hop.nvim version: Commit df0b5b693ef8c3d414b5b85e4bc11cea99c4958d

**Additional context**

**Comment by AdamSundberg** [comment]
Okey, my bad, I found the solution. You have to have an empty `opts` in the lua plugin config, even though you don't have any opts. This maybe could be improved or clarified.

**Comment by jsonMartin** [comment]
> Okey, my bad, I found the solution. You have to have an empty `opts` in the lua plugin config, even though you don't have any opts. This maybe could be improved or clarified.

Thank you, this comment fixed my problem. I wondered why I was having errors hopping from an empty line. I changed `lua require( 'hop').setup()` -> `lua require( 'hop').setup({})` and this fixed my problem.
