### ISSUE TITLE
Hop target incorrectly positioned for lsp inlay hints

### ISSUE THREAD

**Issue by mikavilpas** [smoka7/hop.nvim#64]
**Describe the bug**
When I have this code (notice the inlay hints which are some kind of virtual text)
<img width="451" alt="image" src="https://github.com/smoka7/hop.nvim/assets/300791/36d1a6b3-3d18-424d-b159-d43b2342fcfc">

and I want to jump to the first `'` character. I see this
<img width="444" alt="image" src="https://github.com/smoka7/hop.nvim/assets/300791/e21624ce-4140-4468-9a15-11d799224762">

**To Reproduce**
Let me know if you would like me to provide code for a full repro. I don't have the time to do it right now as the setup is a bit confusing to me and it will take some time.

**Expected behavior**
The hop target should be displayed on the `'` character. It was unexpectedly displayed on the inlay hint instead.

**version (please complete the following information):**
 - Nvim version: `NVIM v0.10.0-dev-2086+g965dbd0e0`
 - hop.nvim version: `6d853addd6e11df8338b26e869a29b36f2c3e893`

**Additional context**
My hop config:
```lua
---@type LazySpec
return {
  "smoka7/hop.nvim",
  version = "*",
  event = "VeryLazy",
  opts = {},
  keys = {
    {
      "<leader>y",
      mode = { "n", "x", "o" },
      function()
        local hop = require("hop")
        hop.hint_lines_skip_whitespace({})
      end,
      desc = "Hop to line",
    },

    {
      "<leader><leader>",
      mode = { "n", "x", "o" },
      function()
        local hop = require("hop")
        hop.hint_char1({})
      end,
      desc = "Hop to given character",
    },
  },
}
```

**Comment by smoka7** [comment]
That's the behaviour of nvim.
To reprooduce : `nvim --clean -u minimal.lua` 
```lua vim.api.nvim_buf_set_lines(0, 0, 0, false, {'this is the first line'})
local ns = vim.api.nvim_create_namespace("a")
vim.api.nvim_buf_set_extmark(
	0,
	ns,
	0,
	3,
	{ end_row = 0, end_col = 3, virt_text_pos = "overlay", virt_text = { { "#", "CurSearch" } }, priority = 100 }
)
vim.api.nvim_buf_set_extmark(
	0,
	ns,
	0,
	3,
	{ end_row = 0, end_col = 3, virt_text_pos = "inline", virt_text = { { "mark", "Search" } }, priority = 100 }
) 
```
You could report it at nvim repo.

**Comment by mikavilpas** [comment]
I see, that's okay. Not a big issue for me.

I'll close this now as I use inlay hints quite rarely :)
