### ISSUE TITLE
Allow Custom Distance Function or Support Read-wise Distance

### ISSUE THREAD

**Issue by johnlevidy** [smoka7/hop.nvim#66]
I would like to be able to rely on the first 3 hops ( read top to bottom, left to right ) being labeled 'a', 's', 'd' ( rather than Manhattan distance ). For example, in the following case:
```
abcdefghijklmnopqrstuvwxyz
this is the z i mean
```
If I start with my cursor on the k and single char hop to "z", the "a" ends up on the z on the line below, which frequently leads to me deleting more than I intend, since I always scan lines left to right before top to bottom.

I would like to provide my own scoring function ( rather than xbias ) which always orders higher lines first and always orders leftmost characters first. That way I can rely on usages like: "`dft<target>a`" always being safe ( and especially, means in the common case I don't even need to read the targets -- even if it's additional keystrokes it is a sequence I can rely on ).

I'm happy to take a stab at the changes myself if there's appetite for it!

My initial thought was that config could just take a custom function similar to x_bias which receives the same parameters ( minus bias of course ).

**Comment by johnlevidy** [comment]
@smoka7 Do you have any preference as to whether this is implemented as a general custom function users can provide in defaults vs. an enum that switches between available functions further down vs. having the function itself ( including manh_distance ) defined in defaults?

**Comment by smoka7** [comment]
When making `x_bias` configurable, I played around with idea of providing some alternative distance functions to `manh_distance`. But they didn't make that much of a change to hints ordering.
I think having a custom sort function and ability to limit the hint count will be more useful to users.

**Comment by johnlevidy** [comment]
manh distance and read-wise distance should give you quite different hint orderings, let me give it a try and make sure it gives the result I expect.  

my concern with providing a custom sort function is by the point you're sorting it all you have are distances, and that it won't enable me to guarantee the next 3 results ( read-wise ) are a, s, d, respectively.

**Comment by smoka7** [comment]
> maybe I misunderstood — by “sort function” do you mean distance function?

By sort i mean `sort_indirect_jump_targets` in `jump_target` module.

**Comment by johnlevidy** [comment]
I submitted a pull request for custom distance functions and confirmed it works to solve the readwise problem and yields consistent ordering.

**Comment by smoka7** [comment]
Thank you for your contribution, I'm a bit busy right now. I'll review in couple of days.
