### ISSUE TITLE
case_insensitive Isn't working

### ISSUE THREAD

**Issue by carlos-algms** [smoka7/hop.nvim#74]
**Describe the bug**
Setting the `case_insensitive = false,` on the `opts` key and then running commands like: `:HopChar1` doesn't seem to be working

**To Reproduce**
```
-- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
        end
        vim.opt.runtimepath:prepend(lazypath)

-- install hop.nvim
        local plugins = {
          { 
            "smoka7/hop.nvim", 
            opts = { 
               case_insensitive = false, 
            } 
          },
        }
        require("lazy").setup(plugins,{})
--- How You use hop...

:HopChar1

```
**Expected behavior**
It should respect the `case_insensitive` prop and only highlight the matching capital letters.

**version (please complete the following information):**
 - Nvim version: 0.9.5
 - hop.nvim version: * (latest)

**Comment by teddywaweru** [comment]
case_insensitive is in the config, not the opts table:
```
require("hop").setup { 

keys = 'etovxqpdygfblzhckisuran',
case_insensitive = false
 }
Though it is a bit awkward, since it'll apply to all hop autocmds...

**Comment by carlos-algms** [comment]
the `opts` table should be passed to `setup(...)` automatically by lazy.
