### ISSUE TITLE
Improving the docs: the wiki is still referring to `phaazon/hop.nvim`

### ISSUE THREAD

**Issue by kohane27** [smoka7/hop.nvim#75]
Thank you for picking up this awesome plugin. I'm really enjoying it!

The [wiki](https://github.com/smoka7/hop.nvim/wiki/Get-started) is still referring to the old repo `phaazon/hop.nvim`. Is it possible that the wiki will allow community edit (or at least submit a PR) so that people can update and improve upon it?

Thank you again!

**Comment by smoka7** [comment]
I opened the wiki edit for the public.
